### PR TITLE
build: upgrade Gatsby to v3

### PR DESCRIPTION
**Pull request by axe312ger**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Would love to see this merged!

**Comment by KyleAMathews** [comment]
Here's what I needed to get this upgraded https://github.com/KyleAMathews/my-very-sweet-contentful-blog/commit/dc754e1c0be8986ff4b684622d82b3ac65c9ba38

It's missing still the conversion from gatsby-image to gatsby-plugin-image

**Comment by davidfateh** [comment]
I think we are good to close this PR after #168 shipped.

**Comment by fk** [comment]
(FWIW: Belated apologies being seemingly ignorant about this! 🙏)

**Pull request closed without merging**
