### PR TITLE
require the same node version as Gatsby

### PR DESCRIPTION
**Pull request by axe312ger**
As Gatsby requires Node 10 since Dec 2019, this starter should do so as well.

### CODE REVIEW

**Comment by jo-sm** [comment]
I think this makes sense -- could you also add an `.nvmrc` with the same version so that it's easy to go `nvm use` when in the repository, please? 

This should also be able to close https://github.com/contentful/starter-gatsby-blog/issues/96 once this is merged.

**Comment by axe312ger** [comment]
@jo-sm added the nvmrc. Did not find a way to tell it "anything above 10.13", so I just use v10 which will use the installed node v10 which is pretty likely to be newer as 10.13

**Comment by jo-sm** [comment]
You can peg a specific version (for example, our `.npmrc` file is `v10.15.3` in the app), but yeah I think you're right in that you can't peg to a version or higher. Since we can't, I think we should at least make the versions in `package.json` and `.npmrc` the same to prevent any possible weird edge cases that could happen.

**Comment by axe312ger** [comment]
@jo-sm I am pretty sure, if we fix it to a specific version number, it will require users downgrade their up2date v10 to `v10.15.3` :(

**Comment by jo-sm** [comment]
That's a good point... and it's clear enough in the `package.json` file. Let's 🚢 it!

**Pull request merged**
